workflows:
    -unity-ios-release-workflow:
      name: Unity iOS release workflow
      max_build_duration: 120
      environment:
          ios_signing:
              distribution_type: app_store
              bundle_identifier: io.codemagic.unitysample
          groups:
            - unity
            - ios_credentials
          vars:
            UNITY_BIN: ${UNITY_HOME}/Contents/MacOS/Unity
            BUILD_SCRIPT: BuildIos 
            UNITY_IOS_DIR: ios
            XCODE_PROJECT: "Unity-iPhone.xcodeproj"
            XCODE_SCHEME: "Unity-iPhone"
            BUNDLE_ID: com.asm.e4st3rnl3g3nds
            APP_STORE_APP_ID: 6503296710
      scripts:
        - name: Initialize macOS keychain
          script: |
            keychain initialize  
        - name: Activate Unity License
          script: | 
            $UNITY_BIN -batchmode -quit -logFile -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
        - name: Generate the Xcode project from Unity
          script: | 
              $UNITY_HOME/Contents/MacOS/Unity -batchmode \
                -quit \
                -logFile \
                -projectPath . \
                -executeMethod BuildScript.BuildIos \
                -nographics
        - name: Set up code signing settings on Xcode project
          script: | 
           xcode-project use-profiles
        - name: Build the project
          script: | 
             xcode-project build-ipa --project "$UNITY_IOS_DIR/$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
      artifacts:
            - build/ios/ipa/*.ipa
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      publishing:
            scripts:
              - name: Deactivate Unity License
                script: $UNITY_BIN -batchmode -quit -returnlicense -nographics
            app_store_connect:            
              api_key: $APP_STORE_CONNECT_PRIVATE_KEY         
              key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
              issuer_id: $APP_STORE_CONNECT_ISSUER_ID
