workflows:
   -unity-ios-release-workflow:
      name: Unity iOS release workflow
      max_build_duration: 120
environment:
   groups:
      - 584
      - 584_ioscred
vars:
  UNITY_BIN: ${UNITY_HOME}/Contents/MacOS/Unity
  BUILD_SCRIPT: BuildIos 
  UNITY_IOS_DIR: ios
  XCODE_PROJECT: "Unity-iPhone.xcodeproj"
  XCODE_SCHEME: "Unity-iPhone"
  BUNDLE_ID: com.asm.e4st3rnl3g3nds
  APP_STORE_APP_ID: 6503296710
scripts:
  - name: Hello world
    script: -echo "Hello"
  - name: Initialize macOS keychain
    script: keychain initialize  
  - name: Activate Unity License
    script: | 
      $UNITY_BIN -batchmode -quit -logFile -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
  - name: Build the Xcode project
    script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScript.$BUILD_SCRIPT -nographics
  - name: Fetch signing files
    script: app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE
  - name: Add certificates to default keychain
    script: keychain add-certificates
  - name: Set up code signing settings on Xcode project
    script: xcode-project use-profiles
  - name: Increment build number
    script: | 
      cd ios && agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
  - name: Build ipa for distribution
    script: xcode-project build-ipa --project "$UNITY_IOS_DIR/$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
artifacts:
      - build/ios/ipa/*.ipa
publishing:
  scripts:
    - name: Deactivate Unity License
      script: $UNITY_BIN -batchmode -quit -returnlicense -nographics
  app_store_connect:            
    api_key: $APP_STORE_CONNECT_PRIVATE_KEY         
    key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
    issuer_id: $APP_STORE_CONNECT_ISSUER_ID
